title: SCORES
email: bqi1@gradcenter.cuny.edu
description: >- # this means to ignore newlines until "baseurl:"
  A lightweight public website for browsing and displaying a small musical corpus.
baseurl: "/AMS-TESTING" # the subpath of your site, e.g. /blog
url: "https://bqicex.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: bqicex
theme: minima
